# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileOwl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('sha1', models.CharField(max_length=20, unique=True)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=200)),
                ('kind_of', models.CharField(max_length=20)),
                ('display_name', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('component', models.ManyToManyField(blank=True, null=True, related_name='self_components', to='draw.PhysicalEntity')),
                ('file_owl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.FileOwl')),
                ('member_physical_entity', models.ManyToManyField(blank=True, null=True, to='draw.PhysicalEntity')),
            ],
        ),
    ]
