# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileowl',
            name='name',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='fileowl',
            name='sha1',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
