# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_auto_20160313_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileowl',
            old_name='name',
            new_name='path_name',
        ),
    ]
