# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_auto_20160313_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalentity',
            name='component',
            field=models.ManyToManyField(blank=True, related_name='self_components', to='draw.PhysicalEntity'),
        ),
        migrations.AlterField(
            model_name='physicalentity',
            name='member_physical_entity',
            field=models.ManyToManyField(blank=True, to='draw.PhysicalEntity'),
        ),
    ]
