# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_fileowl_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalentity',
            name='kind_of',
            field=models.CharField(choices=[('Complex', 'Complex'), ('PhysicalEntity', 'PhysicalEntity'), ('Dna', 'Dna'), ('DnaRegion', 'DnaRegion'), ('Protein', 'Protein'), ('Rna', 'Rna'), ('RnaRegion', 'RnaRegion'), ('SmallMolecule', 'SmallMolecule')], max_length=20),
        ),
    ]
