# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0006_auto_20160314_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalentity',
            name='display_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
