# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_auto_20160318_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalentity',
            name='id_in_file',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
