# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0008_physicalentity_id_in_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalentity',
            name='id_in_file',
            field=models.IntegerField(null=True),
        ),
    ]
