# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_auto_20160318_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalentity',
            name='display_name',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
